name: Cleanup Old Media Files

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  delete_old_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find and delete old files
        run: |
          TARGET_DIR="uploads"
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          current_ts=$(date +%s)
          
          aac_cutoff=$((current_ts - (3 * 3600)))
          mp4_cutoff=$((current_ts - (90 * 60)))
          
          if [ ! -d "$TARGET_DIR" ]; then
            exit 0
          fi

          find $TARGET_DIR -name "*.aac" | while read file; do
            file_ts=$(git log -1 --format=%ct -- "$file")
            if [ -z "$file_ts" ]; then continue; fi

            if [ $file_ts -lt $aac_cutoff ]; then
              git rm "$file"
            fi
          done

          find $TARGET_DIR -name "*.mp4" | while read file; do
            file_ts=$(git log -1 --format=%ct -- "$file")
            if [ -z "$file_ts" ]; then continue; fi

            if [ $file_ts -lt $mp4_cutoff ]; then
              git rm "$file"
            fi
          done
          
          if git diff --staged --quiet; then
            echo "No files to delete."
          else
            git commit -m "Auto-delete old media files [Bot]"
            git push
          fi
